name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: KPIT

      - name: Build
        run: npm run build
        working-directory: KPIT

      - name: Deploy to AWS EC2
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: test4
          remote_host: 18.224.215.214
          remote_user: ec2-user
          remote_key: test4.pem
